src/objects/ApexTruth__c.object
<CustomObject>
    <description>Used to validate expected behavior in Apex, especially for key assumptions made by the trigger workflow framework</description>
    <fields>
        <fullName>NumberOfDmlOperations__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The number of discrete DML operations that have been performed on this record, including the very first insert operation. This counter is managed by a trigger workflow.</description>
        <inlineHelpText>The number of discrete DML operations that have been performed on this record, including the very first insert operation</inlineHelpText>
        <label>Num DML Operations</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Apex Truth</label>
    <nameField>
        <label>Apex Truth Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apex Truths</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ApexTruthTrackDmlWorkflow.cls
global with sharing class ApexTruthTrackDmlWorkflow
        extends AbstractSobjectWorkflow {

    global override void executeAfter() {
        /* do nothing */
    }

    global override void executeBefore() {
        for (ApexTruth__c eachRecord : (List<ApexTruth__c>)this.records) {
            eachRecord.NumberOfDmlOperations__c++;
        }
    }

    /**
     * Any time there's a DML operation we should be tracking that an operation
     * occurred.
     */
    global override Boolean qualify(Sobject newRecord, Sobject oldRecord) {
        return this.context.isInsert || this.context.isUpdate;
    }
}