src/objects/ApexTruth__c.object
<CustomObject>
    <description>Used to validate expected behavior in Apex, especially for key assumptions made by the trigger workflow framework</description>
    <fields>
        <fullName>NumberOfDmlOperations__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The number of discrete DML operations that have been performed on this record, including the very first insert operation. This counter is managed by a trigger workflow.</description>
        <inlineHelpText>The number of discrete DML operations that have been performed on this record, including the very first insert operation</inlineHelpText>
        <label>Num DML Operations</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NumberOfTriggerTouches__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The number of times triggers on the object have been run, as measured by a trigger workflow that increments this field by one in every possible before insert/update context</description>
        <inlineHelpText>The number of times triggers on the object have been run</inlineHelpText>
        <label>Num Trigger Touches</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NumberOfWorkflowTouches__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The number of times a round of workflow field updates has been performed on this object, as measured and tracked by the Set Num Workflow Touches workflow rule</description>
        <inlineHelpText>The number of times a round of workflow field updates has been performed on this object</inlineHelpText>
        <label>Num Workflow Touches</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Apex Truth</label>
    <nameField>
        <label>Apex Truth Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apex Truths</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ApexTruthTrackDmlWorkflowTest.cls
@isTest
private class ApexTruthTrackDmlWorkflowTest {

    /**
     * After a record is inserted where nothing special happens other
     * than the Set Num Workflow Touches workflow rule, the key fields
     * on the Apex truth should show the following.
     *
     * - 1 DML operation
     * - 1 workflow touch
     * - 2 trigger touches, with the 2nd one occurring as a result
     *   of the Num Workflow Touches field update being executed
     */
    @isTest
    private static void validateAutomationCounters() {

        // Define parameters for the test
        ApexTruth__c truth = new ApexTruth__c(Name = 'Iron Man (TEST)');

        // Run the test
        Test.startTest();

        insert truth;

        // Validate results
        truth = [
            SELECT
                NumberOfDmlOperations__c,
                NumberOfWorkflowTouches__c,
                NumberOfTriggerTouches__c
            FROM ApexTruth__c
            WHERE Id = :truth.Id
        ];

        System.assertEquals(1, truth.NumberOfWorkflowTouches__c,
                ApexTruth__c.fields.NumberOfWorkflowTouches__c.getDescribe().getLabel());

        System.assertEquals(1, truth.NumberOfDmlOperations__c,
                ApexTruth__c.fields.NumberOfDmlOperations__c.getDescribe().getLabel());
    }
}