src/objects/ApexTruth__c.object
<CustomObject>
    <description>Used to validate expected behavior in Apex, especially for key assumptions made by the trigger workflow framework</description>
    <fields>
        <fullName>NumberOfTriggerTouches__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The number of times triggers on the object have been run, as measured by a trigger workflow that increments this field by one in every possible before insert/update context</description>
        <inlineHelpText>The number of times triggers on the object have been run</inlineHelpText>
        <label>Num Trigger Touches</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Apex Truth</label>
    <nameField>
        <label>Apex Truth Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apex Truths</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ApexTruthTrackTriggerWorkflow.cls
global with sharing class ApexTruthTrackTriggerWorkflow
        extends AbstractSobjectWorkflow {

    global override void executeAfter(Sobject record) {
        /* do nothing */
    }

    global override void executeBefore(Sobject record) {
        ApexTruth__c truth = (ApexTruth__c)record;
        truth.NumberOfTriggerTouches__c++;
    }

    /**
     * Any time there's a DML operation we should be tracking that an operation
     * occurred.
     */
    global override Boolean qualify(Sobject newRecord, Sobject oldRecord) {
        return Trigger.isInsert || Trigger.isUpdate;
    }
}