src/objects/TriggerWorkflow__mdt.object
<CustomObject>
    <description>Enumeration of trigger workflow implementations, used for turning workflows on and off via configuration instead of with deployments</description>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Whether the workflow should be evaluated. This overrides any entry criteria or any code in the workflow implementation, and every workflow implementation must have a corresponding Trigger Workflow record.</description>
        <inlineHelpText>Whether the workflow should be evaluated</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger Workflow</label>
    <pluralLabel>Trigger Workflows</pluralLabel>
</CustomObject>

force-app/main/default/objects/TriggerWorkflow__mdt/fields/IsOnAfter__c.field-meta.xml
<CustomField>
    <fullName>IsOnAfter__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether the workflow should execute in "after" contexts</description>
    <inlineHelpText>Whether the workflow should execute in "after" contexts</inlineHelpText>
    <label>On After</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerWorkflow__mdt/fields/IsOnBefore__c.field-meta.xml
<CustomField>
    <fullName>IsOnBefore__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether the workflow should execute in "before" contexts</description>
    <inlineHelpText>Whether the workflow should execute in "before" contexts</inlineHelpText>
    <label>On Before</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerWorkflow__mdt/fields/IsOnDelete__c.field-meta.xml
<CustomField>
    <fullName>IsOnDelete__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether the workflow should execute in "delete" contexts</description>
    <inlineHelpText>Whether the workflow should execute in "delete" contexts</inlineHelpText>
    <label>On Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerWorkflow__mdt/fields/IsOnInsert__c.field-meta.xml
<CustomField>
    <fullName>IsOnInsert__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether the workflow should execute in "insert" contexts</description>
    <inlineHelpText>Whether the workflow should execute in "insert" contexts</inlineHelpText>
    <label>On Insert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerWorkflow__mdt/fields/IsOnUndelete__c.field-meta.xml
<CustomField>
    <fullName>IsOnUndelete__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether the workflow should execute in "undelete" contexts</description>
    <inlineHelpText>Whether the workflow should execute in "undelete" contexts</inlineHelpText>
    <label>On Undelete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerWorkflow__mdt/fields/IsOnUpdate__c.field-meta.xml
<CustomField>
    <fullName>IsOnUpdate__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether the workflow should execute in "update" contexts</description>
    <inlineHelpText>Whether the workflow should execute in "update" contexts</inlineHelpText>
    <label>On Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerWorkflow__mdt/fields/SobjectName__c.field-meta.xml
<CustomField>
    <fullName>SobjectName__c</fullName>
    <description>The full API name of the object for which this workflow is executed. This is used primarily as a filter when querying metadata to look for active workflows.</description>
    <inlineHelpText>The full API name (e.g., &quot;Account&quot;, &quot;SBQQ__Quote__c&quot;) of the object for which this workflow is executed</inlineHelpText>
    <label>Object API Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TriggerWorkflowSelector.cls
public with sharing class TriggerWorkflowSelector
extends AbstractSobjectSelector {

    public static Schema.SObjectField getOnBeforeOrAfterField(
        TriggerWorkflowContext context
    ) {
        return context.isBefore
                ? TriggerWorkflow__mdt.IsOnBefore__c
                : context.isAfter
                        ? TriggerWorkflow__mdt.IsOnAfter__c
                        : null;
    }

    public static Schema.SObjectField getOnCrudField(
        TriggerWorkflowContext context
    ) {
        Schema.SObjectField field = null;

        if (context.isUpdate) {
            field = TriggerWorkflow__mdt.IsOnUpdate__c;
        }
        else if (context.isInsert) {
            field = TriggerWorkflow__mdt.IsOnInsert__c;
        }
        else if (context.isDelete) {
            field = TriggerWorkflow__mdt.IsOnDelete__c;
        }
        else if (context.isUndelete) {
            field = TriggerWorkflow__mdt.IsOnUndelete__c;
        }

        return field;
    }

    public List<Schema.SObjectField> getSobjectFields() {
        return new List<Schema.SObjectField> {
            TriggerWorkflow__mdt.DeveloperName,
            TriggerWorkflow__mdt.Id,
            TriggerWorkflow__mdt.IsActive__c,
            TriggerWorkflow__mdt.SobjectName__c
        };
    }

    public Schema.SObjectType getSobjectType() {
        return TriggerWorkflow__mdt.sobjectType;
    }

    public List<TriggerWorkflow__mdt> selectActiveBySobjectNameAndContext(
        String sobjectName,
        TriggerWorkflowContext context
    ) {
        return this.execute(
            this.getQuery().expressWhere(
                Soql.expressAnd(
                    new List<Soql.ConditionExpression> {
                        Soql.expressEquals(
                            TriggerWorkflow__mdt.SobjectName__c,
                            sobjectName
                        ),
                        Soql.expressEquals(
                            getOnBeforeOrAfterField(context),
                            true
                        ),
                        Soql.expressEquals(
                            getOnCrudField(context),
                            true
                        ),
                        Soql.expressEquals(
                            TriggerWorkflow__mdt.IsActive__c,
                            true
                        )
                    }
                )
            )
        );
    }
}